image: docker:latest

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  image: laravelsail/php83-composer:latest
  services:
    - postgres:15
  variables:
    POSTGRES_DB: ip_management
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    DB_CONNECTION: pgsql
    DB_HOST: postgres
    DB_PORT: 5435
    DB_DATABASE: ip_management
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
  before_script:
    - cp backend/.env.example backend/.env
    - sed -i 's/DB_HOST=.*/DB_HOST=postgres/' backend/.env
    - cd backend
    - composer install --no-interaction --prefer-dist
    - php artisan key:generate
    - php artisan migrate --force
  script:
    - php artisan test --parallel

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  when: on_success