version: "3.8"
services:
  db_master:
    image: postgres:15
    container_name: db_master
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - db_master_data:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      - POSTGRES_DB=db_master
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build:
      context: ./backend
    container_name: laravel_app_police
    restart: on-failure
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
      - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
      - /var/www/html/vendor
    networks:
      - app_network
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:Fz9MpgEpswCWwXBBJpM86y+b1tMWnGMTsFACdAzbJb8=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DB_HOST=db_master
      - DB_PORT=5432
      - DB_DATABASE=db_master
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db_master

networks:
  app_network:
    driver: bridge

volumes:
  db_master_data: